### ISSUE TITLE
PSI PROBE Version 4.1.0  Error: java.lang.ClassNotFoundException: org.apache.openejb.loader.Files

### ISSUE THREAD

**Issue by Ramos82** [psi-probe/psi-probe#2982] opened 2023-12-13 14:50 UTC
[trace-20231213-141537-873.zip](https://github.com/psi-probe/psi-probe/files/13662040/trace-20231213-141537-873.zip)

Error: 	java.lang.ClassNotFoundException: org.apache.openejb.loader.Files
exception
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/openejb/loader/Files
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1087)
at psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:86)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:515)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:583)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:212)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:352)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:117)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:126)
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:120)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107)
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:93)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:150)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:117)
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:361)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:225)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:190)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:189)
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:101)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:181)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:156)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:598)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
at psiprobe.Tomcat85AgentValve.invoke(Tomcat85AgentValve.java:38)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:679)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:765)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:617)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:934)
at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.doRun(AprEndpoint.java:2101)
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:750)

Caused by: java.lang.NoClassDefFoundError: org/apache/openejb/loader/Files
at psiprobe.controllers.deploy.UploadWarController.handleRequestInternal(UploadWarController.java:189)
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:177)
at psiprobe.controllers.deploy.UploadWarController.handleRequest(UploadWarController.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072)
... 56 more

Caused by: java.lang.ClassNotFoundException: org.apache.openejb.loader.Files
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1338)
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1150)
... 70 more

**Comment by hazendaz** [comment] 2023-12-22 23:16
@Ramos82 Any feedback here would be helpful.  What version of software are you using?  Are your libs in tomcat lib directory, etc?  If this is a bug on our end, I'd like to fix as quickly as possible as I plan some breaking changes otherwise in 4.2, 4.3, 4.4, and 4.5 as I aggressively try to modernize this.

**Comment by ralf-devop** [comment] 2024-02-13 15:36
I get the same exception after upload a .war file.

13-Feb-2024 14:36:57.272 SEVERE [https-openssl-apr-8444-exec-24] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [probe] in context with path [/probe] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: org/apache/openejb/loader/Files] with root cause
        java.lang.ClassNotFoundException: org.apache.openejb.loader.Files

My enviroment:

Red Hat Enterprise Linux 8.8
Tomcat 9.0.62-18.redhat_00016.1.el8jws
java-11-openjdk 11.0.21.0.9-2.el8
or
java-17-openjdk 17.0.9.0.9-2.el8

PS: psi-probe 4.0.0 works fine!

**Comment by hazendaz** [comment] 2024-02-15 00:16
found the issue.  Wrong import usage on 2 classes.  Will get a patch out this coming weekend.

**Comment by hazendaz** [comment] 2024-02-15 00:19
For reference, issue was committed here https://github.com/psi-probe/psi-probe/commit/84b927412f3ca65fae81ac7a2fca7be1fdda0d57

**Closed** 2024-02-15 02:09 UTC

**Comment by hazendaz** [comment] 2024-02-17 19:11
@ralf-devop @Ramos82 Release 4.1.2 has been completed.  It will be fully available in next few hours.  Please pick up 4.1.2 and confirm issues resolved.

**Comment by ralf-devop** [comment] 2024-02-19 06:16
[localhost.2024-02-19.log](https://github.com/psi-probe/psi-probe/files/14327133/localhost.2024-02-19.log)
By using Release 4.1.2, i get a NoSuchFileException after upload a .war file. @hazendaz see attached logfile.

**Comment by hazendaz** [comment] 2024-02-20 23:32
@ralf-devop What was the last version working for you so I know where to focus on the changes?

**Comment by ralf-devop** [comment] 2024-02-21 07:47
@hazendaz
The last working version for me was 4.0.0.
4.1.0 & 4.1.1 -> ClassNotFoundException
4.1.2 -> NoSuchFileException

In spite of this exceptions the .war file was successfully deployed.
But i won't provide psi-probe to our production stage under this conditions.

**Comment by hazendaz** [comment] 2024-02-22 23:42
Thanks @ralf-devop.  I had replaced the deletion logic there with newer apis and failed to take into account the file is moved and if successful will not exist there.  Pushing a release shortly to address issue in both upload war and copy single file controllers.

**Comment by hazendaz** [comment] 2024-02-23 02:06
@ralf-devop Its released now as 4.1.3.  Sorry about the issues there, should be good to go now.  Let me know if you see any other issues.  Thanks.

**Comment by ralf-devop** [comment] 2024-02-23 11:01
Version 4.1.3 works for me so far. Thank you for your efforts @hazendaz.
In fact, i get another excpetion but thats's a new issue.
