### ISSUE TITLE
Feedback PRE-Release 3.0 Estimate Session Size

### ISSUE THREAD

**Issue by langmar** [psi-probe/psi-probe#983] opened 2017-01-11 08:26 UTC
Estimate Session Size does not work in our environment. No error in probe.log file, but in Tomcat 8.5.0 "localhost" file:

11-Jan-2017 09:22:40.052 SEVERE [http-nio-8095-exec-21] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [probe] in context with path [/probe] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Ljavax/validation/ValidatorFactory;] with root cause
 java.lang.ClassNotFoundException: javax.validation.ValidatorFactory
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1299)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1133)
	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getDeclaredFields(Class.java:1916)
	at psiprobe.tools.Instruments.sizeOfObject(Instruments.java:170)
	at psiprobe.tools.Instruments.internalSizeOf(Instruments.java:145)
	at psiprobe.tools.Instruments.sizeOf(Instruments.java:118)
	at psiprobe.tools.ApplicationUtils.getApplicationSession(ApplicationUtils.java:258)
	at psiprobe.controllers.sessions.ListSessionAttributesController.handleContext(ListSessionAttributesController.java:40)
	at psiprobe.controllers.AbstractContextHandlerController.handleRequestInternal(AbstractContextHandlerController.java:37)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:86)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:121)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:632)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at psiprobe.Tomcat85AgentValve.invoke(Tomcat85AgentValve.java:40)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1096)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:760)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

**Comment by hazendaz** [comment] 2017-01-11 11:49
Can you do me a favor and try tomcat 8.5.9 to see if this is all tomcat 8.5?

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Jan 11, 2017 at 3:26 AM -0500, "Martin Lang" <notifications@github.com<mailto:notifications@github.com>> wrote:


Estimate Session Size does not work in our environment. No error in probe.log file, but in Tomcat 8.5.0 "localhost" file:

11-Jan-2017 09:22:40.052 SEVERE [http-nio-8095-exec-21] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [probe] in context with path [/probe] threw exception [Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Ljavax/validation/ValidatorFactory;] with root cause
java.lang.ClassNotFoundException: javax.validation.ValidatorFactory
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1299)
at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1133)
at java.lang.Class.getDeclaredFields0(Native Method)
at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
at java.lang.Class.getDeclaredFields(Class.java:1916)
at psiprobe.tools.Instruments.sizeOfObject(Instruments.java:170)
at psiprobe.tools.Instruments.internalSizeOf(Instruments.java:145)
at psiprobe.tools.Instruments.sizeOf(Instruments.java:118)
at psiprobe.tools.ApplicationUtils.getApplicationSession(ApplicationUtils.java:258)
at psiprobe.controllers.sessions.ListSessionAttributesController.handleContext(ListSessionAttributesController.java:40)
at psiprobe.controllers.AbstractContextHandlerController.handleRequestInternal(AbstractContextHandlerController.java:37)
at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:174)
at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:50)
at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
at psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:86)
at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:121)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108)
at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:632)
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
at psiprobe.Tomcat85AgentValve.invoke(Tomcat85AgentValve.java:40)
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1096)
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:760)
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1480)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
at java.lang.Thread.run(Thread.java:745)

**Comment by langmar** [comment] 2017-01-11 12:26
Hi,

thank you for your quick reply and all your work for this fantastic project!!

Well, actually we do not have an tomcat 8.5.9 and I am not allowed to install any. Sorry.

But I tested it in tomcat 8.5.5 and it is same behaviour as in 8.5.0.

Here some informations:

Memory utilization
Current memory usage is  62.5%
Free: 750,54 MB Total: 1,96 GB Max: 1,96 GB 
OS information
JVM:  Java(TM) SE Runtime Environment  1.8.0_101-b13  Java HotSpot(TM) 64-Bit Server VM) 
OS: Linux (unknown) amd64 3.0.101-71-default
Processors: 2
Current time: Wed Jan 11 13:19:37 CET 2017
Working dir: /tgc/sfw/apache-tomcat-8.5.5
Container information
Container: Apache Tomcat/8.5.5
catalina.base: /tgc/sfw/apache-tomcat-8.5.5
catalina.home: /tgc/sfw/apache-tomcat-8.5.5
Application base: /tgc/sfw/apache-tomcat-8.5.5/webapps
Configuration base: /tgc/sfw/apache-tomcat-8.5.5/conf/localhost

java.version 1.8.0_101
java.vm.info mixed mode
java.vm.name Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.version 1.8
java.vm.vendor Oracle Corporation
java.vm.version 25.101-b13
os.arch amd64
os.name Linux
os.version 3.0.101-71-default

If there are some other informations I could send you, please let me know. 
Thank you in advance!

Martin

**Comment by hazendaz** [comment] 2017-01-11 12:50
Thanks that will be enough for me to figure this out.

Get Outlook for Android<https://aka.ms/ghei36>



On Wed, Jan 11, 2017 at 7:26 AM -0500, "Martin Lang" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,

thank you for your quick reply and all your work for this fantastic project!!

Well, actually we do not have an tomcat 8.5.9 and I am not allowed to install any. Sorry.

But I tested it in tomcat 8.5.5 and it is same behaviour as in 8.5.0.

Here some informations:

Memory utilization
Current memory usage is  62.5%
Free: 750,54 MB Total: 1,96 GB Max: 1,96 GB
OS information
JVM:  Java(TM) SE Runtime Environment  1.8.0_101-b13  Java HotSpot(TM) 64-Bit Server VM)
OS: Linux (unknown) amd64 3.0.101-71-default
Processors: 2
Current time: Wed Jan 11 13:19:37 CET 2017
Working dir: /tgc/sfw/apache-tomcat-8.5.5
Container information
Container: Apache Tomcat/8.5.5
catalina.base: /tgc/sfw/apache-tomcat-8.5.5
catalina.home: /tgc/sfw/apache-tomcat-8.5.5
Application base: /tgc/sfw/apache-tomcat-8.5.5/webapps
Configuration base: /tgc/sfw/apache-tomcat-8.5.5/conf/localhost

java.version 1.8.0_101
java.vm.info mixed mode
java.vm.name Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.version 1.8
java.vm.vendor Oracle Corporation
java.vm.version 25.101-b13
os.arch amd64
os.name Linux
os.version 3.0.101-71-default

If there are some other informations I could send you, please let me know.
Thank you in advance!

Martin

**Comment by hazendaz** [comment] 2017-01-15 02:41
@langmar javax.validation is not part of tomcat nor part of psi probe.  So it's absense doesn't indicate an issue with psi probe.  My guess is that it's hitting something possibly in an app you have loaded that needs it but is missing.  Can you give me a little more to go on as to what you have setup and have you tried a clean tomcat with only psi probe in it?  I'm not otherwise able to reproduce this issue.

**Comment by hazendaz** [comment] 2017-01-28 04:04
As an interesting side note.  I use psi probe myself with a CDI based application.  It does spit bunches of issues about not being able to find bean manager which I don't feel is a psi probe concern.  Not sure if related or not but for your case I might suggest adding javax.validation-api 1.1.0 to the tomcat lib directory to see if that makes it go away.  I don't have any big concerns about just adding that to psi probe if we can track down why it's needed.

**Comment by hazendaz** [comment] 2018-04-14 04:36
This issue goes away if validation api is added to tomcat/lib.  Closing issue.

**Closed by hazendaz** 2018-04-14 04:36 UTC
