### ISSUE TITLE
Error "/XXX was not installed" on War deployment but still deploys

### ISSUE THREAD

**Issue by pbeutier** [psi-probe/psi-probe#1961] opened 2021-10-11 14:57 UTC
Hello,

I have install the last version of Probe. When I deploy a war file, I have an error "/XXX was not installed" but still deploys the war.

An explanation?

Thx.

**Comment by robygermto** [comment] 2021-12-22 14:33
Hi.

Same issue here.
thank you

**Comment by MarcosRodrigoFerreira** [comment] 2022-05-18 18:45
Hi There,

Do You guys found a solution for this issue?

Same problem here!

Thanks

**Comment by dilanb24** [comment] 2022-05-19 12:12
I have the same issue. The war file is deployed but failed to unpack load into the probe. After restarting the tomcat, the war files is unpacked and the application is on running status in the probe. It is down when I tried to undeploy, but the application is deleted in the webapps folder. Does anyone have a solution?

**Comment by jeanpaixao** [comment] 2022-06-01 21:15
Também passo pelo mesmo problema.

**Comment by galasd** [comment] 2022-06-07 10:20
Same problem here with Probe 3.5.8 and Tomcat 9.0.63

**Comment by desarrollosipcommb** [comment] 2022-09-09 16:41
tengo el mismo problema

**Comment by ZebrasTeam** [comment] 2023-03-06 12:34
Same problem here with Probe 3.7.1 and Tomcat 9.0.62.redhat-00005

**Comment by Xt-Man** [comment] 2023-08-25 13:32
Same problem here
Tested on Probe 3.2.0 to 3.7.x, the problem occurs in all versions

I still have an old server running Probe 3.0.0... work's like a charm. Something is broken after 3.0.0

**Comment by hazendaz** [comment] 2023-08-27 19:13
@Xt-Man If you could, please check diff between 3.0.0 to 3.2.0 and try to isolate that down and possibly raise a PR to resolve.  I don't directly use this project any more but still maintain it.  Issues like this are harder for me to assist on given I don't have a real use case to spend time addressing said issues.

**Comment by Xt-Man** [comment] 2023-08-28 22:57
Hi @hazendaz , i'll try

**Comment by ralf-devop** [comment] 2024-02-26 06:47
I can confirm, this issue still exists in newer versions.
I'am using version 4.1.3 and i observe the same behaviour.

**Comment by ralf-devop** [comment] 2024-02-26 09:03
@hazendaz
I found the reason for this issue.
Upload .war file don't wait for background process finishing.
If i add a breakpoint in class UploadWarController on line 148 
	getContainerWrapper().getTomcatContainer().installWar(contextName);
and wait few seconds during debugging, the next line 
	Context ctx = getContainerWrapper().getTomcatContainer().findContext(contextName);
get the context successfully, otherwise the context is empty.

**Comment by hazendaz** [comment] 2024-03-02 17:08
Will be fixed by #3148.  Not sure this is the best solution but seems to work for @ralf-devop and may just work for others as well.  Will work to release this today most likely if no other better option presents itself so we have a chance of this working well.  If anyone else sees any better way to address, feel free to send a separate PR.  Do note, best way to get some of the general items fixed is to do exactly as @ralf-devop is doing, send PRs as the original team on this is gone and I'm the sole survivor here at the moment and spread pretty thin on stuff I do on github and my paying job.  So any help is so much appreciated.

**Comment by hazendaz** [comment] 2024-03-02 19:34
Closing as this should be resolved with release 4.1.4 which will be out shortly.

**Closed by hazendaz** 2024-03-02 19:34 UTC
