### ISSUE TITLE
Show TrustStore certificates

### ISSUE THREAD

**Issue by sandrapascual** [psi-probe/psi-probe#659] opened 2016-02-08 13:21 UTC
The issue is about showing a list with the certificates contained in TrustStore defined in the System Property "javax.net.ssl.trustStore" sorted by Expiration Date.

This new funcionality will be shown in the system tab down to Wrapper Control.

**Comment by farconada** [comment] 2016-02-08 13:44
It's a great idea. I need something like this to find the root cause of ssl handshake exceptions in fast way

**Comment by hazendaz** [comment] 2016-02-08 17:48
+1


Sent from Outlook Mobile






On Mon, Feb 8, 2016 at 5:46 AM -0800, "Fernando Arconada" <notifications@github.com> wrote:





It's a great idea. I need something like this to find the root cause of ssl handshake exceptions in fast way

---

**Comment by hazendaz** [comment] 2016-02-09 03:08
@farconada ignore previous comment if it reached you.  Posted in wrong spot.

**Comment by diogosantana** [comment] 2016-02-09 21:31
I can try to do this as I have a lot of xp with certificates, jks and SSL/TLS, although it won't be enough to debug ssl handshake exceptions.

**Comment by jander99** [comment] 2016-02-09 21:34
I think the point would be to see whether a keystore has the necessarily
certificates.  For instance, where I work, we have our own internal SSL
CA.  If the JDK is not patched to include the CA's cert, the handshake
fails.  It would be nice to be able to see the list (output from keytool,
basically) of certs and determine if a JDK has the necessarily certs.

**Comment by diogosantana** [comment] 2016-02-09 21:36
I noticed https://github.com/sandrapascual/psi-probe/commit/081ab4039f71276c7c86f877e21980cdd94ee615 commit only list the jvm configured trust stores (`javax.net.ssl.trustStore`) certificates, but tomcat accepts configuration of two stores per connector, the server certificate store and the trusted certificates store.

**Comment by diogosantana** [comment] 2016-02-09 21:38
Oh, I just saw the PR conversation... nvm

**Comment by jander99** [comment] 2016-02-09 21:39
Just to document, you mean the keystoreFile and truststoreFile from the
Connector documentation
https://tomcat.apache.org/tomcat-8.0-doc/config/http.html#SSL_Support ?

**Comment by diogosantana** [comment] 2016-02-09 21:53
Yes. But I do agre with @sandrapascual PR's comment (https://github.com/psi-probe/psi-probe/pull/660#issuecomment-181757598) about put this on system tab and later add per connector config.

Maybe we should add another tab like "Certificates" with all system and per connector configs. Thoughts?

**Comment by hazendaz** [comment] 2016-02-15 03:00
The code for trust store using jvm properties has been merged.  However, we may either want to keep this open or open a new issue regarding some ability to pull this information from tomcats connectors.

**Comment by diogosantana** [comment] 2016-02-15 14:40
I am working on that at https://github.com/diogosantana/psi-probe/commit/03f0133108ad04713e747f2297bb9f698742dee7. Maybe we can close this and open a new Issue?

**Comment by hazendaz** [comment] 2016-02-19 02:15
Initial support for truststore from system perspective as well as keystore/truststore from tomcat connector perspective now on master.

**Closed by hazendaz** 2016-02-19 02:15 UTC
Labels: Type-Feature

**Comment by diogosantana** [comment] 2016-02-19 02:27
Do we keep the wrapper control thing?

**Comment by hazendaz** [comment] 2016-02-19 03:46
I think so.  Based on how tomcat describes it, that sounds like the right spot for the system provided one.

**Comment by diogosantana** [comment] 2016-02-19 03:51
Sorry, I could be understanding this the wrong way, but wrapper service does not only work if you are using org.tanukisoftware.wrapper?

**Comment by hazendaz** [comment] 2016-02-19 03:55
Is that related to this issue?  I looked back over this and wasn't seeing anything.  I haven't used a wrapper in a while.  Can you show what is not working?

**Comment by hazendaz** [comment] 2016-02-19 04:02
@diogosantana What is your email?  I'm going to invite you over to our slack channel if you are interested.  Only three of us in there but could be very useful for further discussions.

**Comment by diogosantana** [comment] 2016-02-19 04:05
Yes, it is related. But I got confused. I did recheck now and it is all fine.
My e-mail is diogosantana@gmail.com
