### ISSUE TITLE
when click on logs, gives NullPointerException at ContainerListenerBean.java:144

### ISSUE THREAD

**Issue by yujiaao** [psi-probe/psi-probe#1054] opened 2017-04-27 10:36 UTC
```
18:11:00.535 INFO  {Probe_Quartz-2} [psiprobe.beans.ContainerWrapperBean] Using DEFAULT resource resolver
18:11:00.550 ERROR {Probe_Quartz-2} [org.quartz.core.JobRunShell] Job DEFAULT.connectorStatsJobDetail threw an unhandled Exception: 
org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean] failed; nested e
xception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.NullPointerException: null
	at psiprobe.beans.ContainerListenerBean.initialize(ContainerListenerBean.java:144)
	at psiprobe.beans.ContainerListenerBean.getConnectors(ContainerListenerBean.java:266)
	at psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean.collect(ConnectorStatsCollectorBean.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 common frames omitted
18:11:00.552 ERROR {Probe_Quartz-2} [org.quartz.core.ErrorLogger] Job (DEFAULT.connectorStatsJobDetail threw an exception.
org.quartz.SchedulerException: Job threw an unhandled exception.
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: org.springframework.scheduling.quartz.JobMethodInvocationFailedException: Invocation of method 'collect' on target class [class psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean] faile
d; nested exception is java.lang.NullPointerException
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:266)
	at org.springframework.scheduling.quartz.QuartzJobBean.execute(QuartzJobBean.java:75)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 common frames omitted
Caused by: java.lang.NullPointerException: null
	at psiprobe.beans.ContainerListenerBean.initialize(ContainerListenerBean.java:144)
	at psiprobe.beans.ContainerListenerBean.getConnectors(ContainerListenerBean.java:266)
	at psiprobe.beans.stats.collectors.ConnectorStatsCollectorBean.collect(ConnectorStatsCollectorBean.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.util.MethodInvoker.invoke(MethodInvoker.java:269)
	at org.springframework.scheduling.quartz.MethodInvokingJobDetailFactoryBean$MethodInvokingJob.executeInternal(MethodInvokingJobDetailFactoryBean.java:257)
	... 3 common frames omitted
18:11:00.997 INFO  {localhost-startStop-1} [psiprobe.ProbeServlet] FrameworkServlet 'probe': initialization completed in 4271 ms
18:11:00.998 INFO  {localhost-startStop-1} [psiprobe.beans.ContainerWrapperBean] Server info: Apache Tomcat/7.0.52 (Ubuntu)
18:11:01.022 INFO  {localhost-startStop-1} [psiprobe.beans.ContainerWrapperBean] Using psiprobe.Tomcat70ContainerAdapter
```

**Comment by hazendaz** [comment] 2017-04-28 01:49
@yujiaao I'm not able to reproduce this condition.  What version of psi-probe are you using?  Also what type of log are you trying to access?

**Comment by yujiaao** [comment] 2017-05-05 05:07
Maybe the log is not relevant, or may be it occurred by large log files, when I clean all old log files, the problem is disappears.

**Comment by hazendaz** [comment] 2023-05-21 03:54
likely no longer an issue, closing.

**Closed by hazendaz** 2023-05-21 03:54 UTC
