### ISSUE TITLE
Paging broken in data sources.

### ISSUE THREAD

**Issue by tonywestonuk** [psi-probe/psi-probe#829] opened 2016-11-25 14:26 UTC
Version 3.0

After running a query that results in multiple pages of results, clicking on any page number results in an error "HTTP Status 405 - Request method 'POST' not supported"

**Comment by hazendaz** [comment] 2016-11-27 04:02
Spring 4.3.x started causing this issue.  If you drop back to 4.2.x, it should work again.  I'm working at trying to resolve this overall but will take some time.  Can you get me a stack trace of the location in question resulting in the 405?  That will help me in finding and resolving such issues.

**Comment by tonywestonuk** [comment] 2016-11-27 20:10
Its not giving me a stack track, but the REST call in question is /probe/sql/cachedRecordset.ajax

hope this helps.

Spring spring spring spring ..... Ugh.  The sooner people move away from this awful framework the better </rant>

**Comment by hazendaz** [comment] 2016-12-09 05:15
@tonywestonuk Any chance I can get a stack trace on this?  I recall you saying it didn't log anything but that shouldn't be.  It should have logged something.

**Comment by hazendaz** [comment] 2016-12-15 17:29
Spring 4.3 issue related to this change in ParameterizableViewController

```java
	public ParameterizableViewController() {
		super(false);
		setSupportedMethods(HttpMethod.GET.name(), HttpMethod.HEAD.name());
	}
```

**Comment by hazendaz** [comment] 2016-12-15 18:20
For reference, see spring for this [commit](https://github.com/spring-projects/spring-framework/commit/135738f9bfb5b9dacf164d6561144589dc98deb8)

I have a hack work around I'll be applying shortly.

Since this is just a duplicate of #788, closing.

**Closed by hazendaz** 2016-12-15 18:20 UTC

**Comment by hazendaz** [comment] 2016-12-15 19:51
@tonywestonuk I cannot confirm this has been fixed on master.  Can you take a look?  If not, if you could get me some basic configuration so I can run this same test, I do have a fix that can be applied quickly.  That or pinpoint the view that breaks with 405.  Thanks.
