### ISSUE TITLE
Psi probe not listing global/application datasources - tomcat

### ISSUE THREAD

**Issue by mbonastre** [psi-probe/psi-probe#490] opened 2015-04-24 10:31 UTC
Maybe this issue is redundant; there are other open issues about datasources, but they are very specific and don't seem to fit this case.

Psi-Probe does not correctly list datasources in Tomcat 6 and 7. In tomcat 8, some datasources are listed, others are not.

The commit d4cceeabf847b449848648639c7bc22c4c38dabd tries to solve it, but it only works partially on Tomcat 8.

I have tested this on:
 - Tomcat 6.0.43
 - Tomcat 7.0.61
 - Tomcat 8.0.21
With probe-2.4.0-SNAPSHOT (20150423 08:59)

What steps will reproduce the problem?
 - Install probe on default tomcat config as described in probe wiki
 - Create one application datasource in file conf/Catalina/localhost/docs.xml

<Context>
<Resource name="jdbc/appOracle" auth="Container"
              type="javax.sql.DataSource" driverClassName="oracle.jdbc.OracleDriver"
              url="jdbc:oracle:thin:@(description=(...))"
              username="xxx" password="xxxx" maxActive="20" maxIdle="10"
              maxWait="-1"/>
</Context>

 - Create on global datasource in GlobalNamingResources in conf/server.xml

<Resource name="jdbc/globalOracle" auth="Container"
              type="javax.sql.DataSource" driverClassName="oracle.jdbc.OracleDriver"
              url="jdbc:oracle:thin:@(description=(...))"
              username="xxx" password="xxxx" maxActive="20" maxIdle="10"
              maxWait="-1"/>
</Context>

 - Add Oracle driver to lib
 - Start tomcat
 - Login to probe
 - Go to "Data Sources" tab

What is the expected result?
  - You should see two datasources: one global, one application

What happens instead?

In tomcat 6 and tomcat 8:
  - Probe shows message "There are no data sources configured for this Tomcat instance"

In tomcat 7:
 - Probe shows only the global datasource

Also, in Tomcat 6 and 7:
  - If you go to Tab "Applications", click on "/docs", select "Resources":
    Shows datasource "jdbc/appOracle" with error:
    "This resource is misconfigured and runtime information is not available"

  - If you then click on "jdbc/appOracle", "Test Connection":
    Shows error "Data source jdbc/appOracle does not exist"

In Tomcat 8:
  - If you go to Tab "Applications", click on "/docs", select "Resources":
    Seems to be ok.
  - If you then click on "jdbc/appOracle", "Test Connection":
    Seems to be ok. (in my case, "Cannot establish a database connection.")

What version of Probe are you using?

probe-2.4.0-SNAPSHOT (20150423 08:59)
This includes commit d4cceeabf847b449848648639c7bc22c4c38dabd 
(Merge pull request #467 from henry-caballero/master)

What environment (browser version, Tomcat version, JVM version, server OS)?

Test 1: Tomcat 6 + java 6
Server version: Apache Tomcat/6.0.43
Server built:   Nov 14 2014 10:04:27 UTC
Server number:  6.0.43.0
OS Name:        Linux
OS Version:     3.2.0-4-amd64
Architecture:   amd64
JVM Version:    1.6.0_34-b34
JVM Vendor:     Sun Microsystems Inc.

Test 2: Tomcat 6 + java 7
Server version: Apache Tomcat/6.0.43
Server built:   Nov 14 2014 10:04:27 UTC
Server number:  6.0.43.0
OS Name:        Linux
OS Version:     3.2.0-4-amd64
Architecture:   amd64
JVM Version:    1.7.0_25-b30
JVM Vendor:     Oracle Corporation

Test 3: Tomcat 6 + java 8
Server version: Apache Tomcat/6.0.43
Server built:   Nov 14 2014 10:04:27 UTC
Server number:  6.0.43.0
OS Name:        Linux
OS Version:     3.2.0-4-amd64
Architecture:   amd64
JVM Version:    1.8.0_40-internal-b27
JVM Vendor:     Oracle Corporation

Test 4: Tomcat 7 + Java 7
Server version: Apache Tomcat/7.0.61
Server built:   Mar 27 2015 12:03:56 UTC
Server number:  7.0.61.0
OS Name:        Linux
OS Version:     3.2.0-4-amd64
Architecture:   amd64
JVM Version:    1.7.0_25-b30
JVM Vendor:     Oracle Corporation

Test 5: Tomcat 7 + Java 8
Server version: Apache Tomcat/7.0.61
Server built:   Mar 27 2015 12:03:56 UTC
Server number:  7.0.61.0
OS Name:        Linux
OS Version:     3.2.0-4-amd64
Architecture:   amd64
JVM Version:    1.8.0_40-internal-b27
JVM Vendor:     Oracle Corporation

Test 6: Tomcat 8 + Java 8
Server version: Apache Tomcat/8.0.21
Server built:   Mar 23 2015 14:11:21 UTC
Server number:  8.0.21.0
OS Name:        Linux
OS Version:     3.2.0-4-amd64
Architecture:   amd64
JVM Version:    1.8.0_40-internal-b27
JVM Vendor:     Oracle Corporation

**Comment by mbonastre** [comment] 2015-04-24 10:42
Also, in production environment, with Tomcat 8 and Java 8 and same version of probe:
- We have 6 appication datasources declared
- Only 3 show on "Data Sources" tab

I still don't know how to replicate this behaviour in a controlled environment. I can't find the difference between the datasources that show and the ones that don't. I'm still trying.

Same application but with Tomcat 6 + Java 6, the error is consistent (no datasource is listed)

**Comment by robertoschwald** [comment] 2015-04-24 13:13
Same problem here. 
Deployed 2.4.0-SNAPSHOT (2862c8f5).
Now the "Name [UserDatabase] is not bound in this Context." error disappeared, but still I get errors for an application defined datasource on Tomcat 7.0.55 / Java 1.7.0_79_x86_64 (Linux)

Probe shows 

    "There are no data sources configured for this Tomcat instance"

under application > resources I get 

    "javax.sql.DataSource exclamation sign This resource is misconfigured and runtime information is not available "

Context file is in conf/Catalina/localhost/demo.xml
```xml
<Context path="/demo" docBase="${catalina.home}/demodir/demo"
         debug="0" reloadable="false" crossContext="false">

  <Logger className="org.apache.catalina.logger.FileLogger" 
    prefix="demo." suffix=".log" timestamp="true"/>

  <Resource name="jdbc/demo" 
        auth="Container" type="javax.sql.DataSource"
        factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
        driverClassName="com.mysql.jdbc.Driver"
        initialSize="2"
        maxActive="30" 
        maxIdle="10" 
        maxWait="100000"
        username="demodbusername" 
        password="XXXXXX" 
        validationQuery="select 1"
        testWhileIdle="true"
        testOnBorrow="true"
        testOnReturn="false"
        timeBetweenEvictionRunsMillis="1800000"
        minEvictableIdleTimeMillis="3600000"
        numTestsPerEvictionRun="10"
        removeAbandonedTimeout="300"
        removeAbandoned="true" 
        logAbandoned="true"
        jdbcInterceptors="ConnectionState;SlowQueryReport(threshold=1500);ResetAbandonedTimer"
        url="jdbc:mysql://localhost:3306/demo"/>
</Context>
```

```log
24 Apr 2015 14:55:49 [ajp-bio-8009-exec-3] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT 
24 Apr 2015 14:55:49 [ajp-bio-8009-exec-3] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /manager
24 Apr 2015 14:55:49 [ajp-bio-8009-exec-3] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /host-manager
24 Apr 2015 14:55:49 [ajp-bio-8009-exec-3] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /demo
24 Apr 2015 14:55:49 [ajp-bio-8009-exec-3] INFO  com.googlecode.psiprobe.Tomcat70ContainerAdaptor  - reading resource: jdbc/demo
24 Apr 2015 14:55:49 [ajp-bio-8009-exec-3] ERROR com.googlecode.psiprobe.beans.ResourceResolverBean  - Failed to lookup: jdbc/demo
javax.naming.NameNotFoundException: Name [jdbc/demo] is not bound in this Context. Unable to find [jdbc].
	at org.apache.naming.NamingContext.lookup(NamingContext.java:819)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:153)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:830)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:153)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:830)
	at org.apache.naming.NamingContext.lookup(NamingContext.java:167)
	at org.apache.naming.SelectorContext.lookup(SelectorContext.java:156)
	at javax.naming.InitialContext.lookup(InitialContext.java:411)
	at com.googlecode.psiprobe.beans.ResourceResolverBean.lookupResource(ResourceResolverBean.java:136)
	at com.googlecode.psiprobe.beans.ResourceResolverBean.getApplicationResources(ResourceResolverBean.java:115)
	at com.googlecode.psiprobe.beans.ContainerWrapperBean.getPrivateDataSources(ContainerWrapperBean.java:177)
	at com.googlecode.psiprobe.controllers.datasources.ListAllJdbcResourcesController.handleRequestInternal(ListAllJdbcResourcesController.java:32)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:875)
	at com.googlecode.psiprobe.ProbeServlet.doDispatch(ProbeServlet.java:55)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:807)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:571)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:501)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:399)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:109)
	at org.springframework.security.intercept.web.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.ui.ExceptionTranslationFilter.doFilterHttp(ExceptionTranslationFilter.java:101)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.ui.logout.LogoutFilter.doFilterHttp(LogoutFilter.java:89)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.ui.preauth.AbstractPreAuthenticatedProcessingFilter.doFilterHttp(AbstractPreAuthenticatedProcessingFilter.java:69)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.context.HttpSessionContextIntegrationFilter.doFilterHttp(HttpSessionContextIntegrationFilter.java:235)
	at org.springframework.security.ui.SpringSecurityFilter.doFilter(SpringSecurityFilter.java:53)
	at org.springframework.security.util.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:411)
	at org.springframework.security.util.FilterChainProxy.doFilter(FilterChainProxy.java:188)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:236)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:167)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:129)
	at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at com.googlecode.psiprobe.Tomcat70AgentValve.invoke(Tomcat70AgentValve.java:39)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
24 Apr 2015 14:55:49 [ajp-bio-8009-exec-3] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading CONTEXT /probe
24 Apr 2015 14:55:49 [ajp-bio-8009-exec-3] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - Reading GLOBAL resources
24 Apr 2015 14:55:49 [ajp-bio-8009-exec-3] INFO  com.googlecode.psiprobe.beans.ResourceResolverBean  - reading resource: Catalina:type=Resource,resourcetype=Global,class=org.apache.catalina.UserDatabase,name="UserDatabase"
```

**Comment by diogosantana** [comment] 2015-05-25 17:19
Tomcat 8 changes tomcat-dbcp package name from org.apache.tomcat.dbcp.dbcp to org.apache.tomcat.dbcp.dbcp2. So datasources don't show up because org.apache.commons.dbcp.BasicDataSource can't find the new package name.

**Comment by MALfunction84** [comment] 2015-07-04 21:50
Are people still having this problem? I'm inclined to punt this so we can release 2.4.0, but I'm afraid it might be a regression.

**Comment by robertoschwald** [comment] 2015-07-05 06:50
Yes, the problem is still there on Tomcat 7.0.55. 
Its easy to cause the problem.

1. Add the mysql-connector jar to tomcat's lib dir
2. Create a MySQL db demo for user demo/demo
3. create file <tomcat_dir>/webapps/demo/WEB-INF/web.xml with content:
{code}
<web-app xmlns="http://java.sun.com/xml/ns/javaee"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
                      http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
  version="3.0"
  metadata-complete="true">
    <description>Demo</description>
    <display-name>Demo app for psi-probe</display-name>
</web-app>
{code}
4. Add the demo.xml file I stated Apr 24 to conf/Catalina/localhost/demo.xml

Then access "Data Sources" in psi-probe. 

Tried now with the latest master. It still does not work.

**Comment by MALfunction84** [comment] 2015-07-05 16:47
So this is occurring in the latest snapshot build of 2.4. Did it also occur in 2.3.3?

**Comment by robertoschwald** [comment] 2015-07-05 17:35
Yes. Sonething changed in Tomcat 7. In older versions it works

Sent while mobile.

**Comment by MALfunction84** [comment] 2015-07-05 22:41
OP mentioned Tomcat 6 and 8 failures as well. There are so many different issues mentioned, I'm not sure I understand the scope of the problem.

**Comment by MALfunction84** [comment] 2015-07-05 22:41
At least it's not a regression between 2.3.3 and 2.4.0...

**Comment by diogosantana** [comment] 2015-07-08 14:12
I believe we can close this in favor of #531 and #534.

**Comment by MALfunction84** [comment] 2015-07-08 22:27
Agreed.

**Closed by MALfunction84** 2015-07-08 22:27 UTC
Labels: bug, FoundIn-Snapshot
