### ISSUE TITLE
probe.war download

### ISSUE THREAD

**Issue by robvoi** [psi-probe/psi-probe#506] opened 2015-05-06 06:58 UTC
Is there a source to download the newest Version as war file?
Would be nice to always be able to get the newest version somewhere.

**Comment by MALfunction84** [comment] 2015-05-06 12:54
Duplicate of #499

**Closed** 2015-05-06 12:54 UTC
Labels: duplicate

**Comment by hazendaz** [comment] 2015-05-20 01:05
You could just manually upload build points. https://github.com/psi-probe/psi-probe/releases
