### ISSUE TITLE
Race condition between main thread and QuartzScheduler worker threads

### ISSUE THREAD

**Issue by GoogleCodeExporter** [psi-probe/psi-probe#404] opened 2015-03-16 15:29 UTC
```
What steps will reproduce the problem?
1. use JDK to 1.7.0_51 on CentOS6_64
2. Set Tomcat to use the AJP13 NIO connector
3. start Tomcat

What is the expected result?
normal startup

What happens instead?
Exception in probe.log. See attachment.


What version of Probe are you using?
2.3.0

What environment (browser version, Tomcat version, JVM version, server OS)?
CentOS 6.5_64 (latest version including the workaround OpenSSL interim package 
issued last night)

Please provide any additional information below.
(Attach logs or stack traces as files instead of pasting the contents
here.)

Tomcat server.xml AJP config:

  <Connector port="8009"
               protocol="org.apache.coyote.ajp.AjpNioProtocol"
               maxThreads="10000"
               connectionTimeout="600000"
               redirectPort="9443" />



JNDI Datasource definition (using context.xml config in conf/Catalina/localhost 
for an application):

   <Resource name="jdbc/xxx" auth="Container" type="javax.sql.DataSource"
               maxActive="100" maxIdle="30" maxWait="10000"
               validationQuery = "select 1"
               testWhileIdle = "true"
               timeBetweenEvictionRunsMillis = "60000"
               removeAbandoned="true" 
               removeAbandonedTimeout="240"
               logAbandoned="true"
               driverClassName="com.mysql.jdbc.Driver"
               username="xxx"
               password="yyy"
               url="jdbc:mysql://localhost:3306/xxx"/>
```

Original issue reported on code.google.com by `robertos...@gmail.com` on 9 Apr 2014 at 8:14

Attachments:
- [probe2.3.0_crash_nio_with_jndi.txt](https://storage.googleapis.com/google-code-attachments/psi-probe/issue-404/comment-0/probe2.3.0_crash_nio_with_jndi.txt)

**Comment by jander99** [comment] 2015-04-09 23:58
Scanning Milestone-2.4.0.  

I'm not sure how to test this, but I noticed that in web.xml, spring-probe-stats.xml is ordered before spring-probe-controllers.xml.  I wonder if because spring-probe-controllers.xml contains references to the container wrapper, that the controllers need to be loaded before the stats beans. I'm not sure quartz can be delayed unless Spring's first invocation of the stats beans and thus creation of the schedule and scheduler thread can be delayed on the main thread until after some other condition (such as completion of ContainerWrapper initialization) is complete.  

About the only thing I can find on delaying quartz is adding the startupDelay to the scheduler bean:

```xml
	<bean name="scheduler" class="org.springframework.scheduling.quartz.SchedulerFactoryBean">
		<property name="triggers">
			<list>
				<ref local="connectorStatsTrigger"/>
				<ref local="clusterStatsTrigger"/>
				<ref local="memoryStatsTrigger"/>
				<ref local="runtimeStatsTrigger"/>
				<ref local="appStatsTrigger"/>
				<ref local="datasourceStatsTrigger"/>
				<ref local="statsSerializerTrigger"/>
			</list>
		</property>
		<property name="startupDelay" value="30" />
	</bean>
```

Source: [spring.io](http://docs.spring.io/spring-framework/docs/2.5.x/api/org/springframework/scheduling/quartz/SchedulerFactoryBean.html#setStartupDelay(int))

**Comment by diogosantana** [comment] 2015-04-22 03:36
I suggest to remove this issue to 2.4 milestone until confirmation by unit test or steps to reproduce.

I tried to reproduce this without sucess.

**Comment by hazendaz** [comment] 2017-01-03 02:30
I do not believe this is an issue plus the entire code base around spring is now changed.  Closing this.

**Closed by hazendaz** 2017-01-03 02:30 UTC
Labels: Attached-Stacktrace, auto-migrated, Type-Bug
